// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ess

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExternalSecretStoreServiceClient is the client API for ExternalSecretStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalSecretStoreServiceClient interface {
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	ApplySecret(ctx context.Context, in *ApplySecretRequest, opts ...grpc.CallOption) (*ApplySecretResponse, error)
	DeleteKeys(ctx context.Context, in *DeleteKeysRequest, opts ...grpc.CallOption) (*DeleteKeysResponse, error)
}

type externalSecretStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalSecretStoreServiceClient(cc grpc.ClientConnInterface) ExternalSecretStoreServiceClient {
	return &externalSecretStoreServiceClient{cc}
}

func (c *externalSecretStoreServiceClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, "/ExternalSecretStoreService/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalSecretStoreServiceClient) ApplySecret(ctx context.Context, in *ApplySecretRequest, opts ...grpc.CallOption) (*ApplySecretResponse, error) {
	out := new(ApplySecretResponse)
	err := c.cc.Invoke(ctx, "/ExternalSecretStoreService/ApplySecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalSecretStoreServiceClient) DeleteKeys(ctx context.Context, in *DeleteKeysRequest, opts ...grpc.CallOption) (*DeleteKeysResponse, error) {
	out := new(DeleteKeysResponse)
	err := c.cc.Invoke(ctx, "/ExternalSecretStoreService/DeleteKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalSecretStoreServiceServer is the server API for ExternalSecretStoreService service.
// All implementations must embed UnimplementedExternalSecretStoreServiceServer
// for forward compatibility
type ExternalSecretStoreServiceServer interface {
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	ApplySecret(context.Context, *ApplySecretRequest) (*ApplySecretResponse, error)
	DeleteKeys(context.Context, *DeleteKeysRequest) (*DeleteKeysResponse, error)
	mustEmbedUnimplementedExternalSecretStoreServiceServer()
}

// UnimplementedExternalSecretStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExternalSecretStoreServiceServer struct {
}

func (UnimplementedExternalSecretStoreServiceServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedExternalSecretStoreServiceServer) ApplySecret(context.Context, *ApplySecretRequest) (*ApplySecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySecret not implemented")
}
func (UnimplementedExternalSecretStoreServiceServer) DeleteKeys(context.Context, *DeleteKeysRequest) (*DeleteKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeys not implemented")
}
func (UnimplementedExternalSecretStoreServiceServer) mustEmbedUnimplementedExternalSecretStoreServiceServer() {
}

// UnsafeExternalSecretStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalSecretStoreServiceServer will
// result in compilation errors.
type UnsafeExternalSecretStoreServiceServer interface {
	mustEmbedUnimplementedExternalSecretStoreServiceServer()
}

func RegisterExternalSecretStoreServiceServer(s grpc.ServiceRegistrar, srv ExternalSecretStoreServiceServer) {
	s.RegisterService(&ExternalSecretStoreService_ServiceDesc, srv)
}

func _ExternalSecretStoreService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalSecretStoreServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExternalSecretStoreService/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalSecretStoreServiceServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalSecretStoreService_ApplySecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalSecretStoreServiceServer).ApplySecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExternalSecretStoreService/ApplySecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalSecretStoreServiceServer).ApplySecret(ctx, req.(*ApplySecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalSecretStoreService_DeleteKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalSecretStoreServiceServer).DeleteKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExternalSecretStoreService/DeleteKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalSecretStoreServiceServer).DeleteKeys(ctx, req.(*DeleteKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalSecretStoreService_ServiceDesc is the grpc.ServiceDesc for ExternalSecretStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalSecretStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ExternalSecretStoreService",
	HandlerType: (*ExternalSecretStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _ExternalSecretStoreService_GetSecret_Handler,
		},
		{
			MethodName: "ApplySecret",
			Handler:    _ExternalSecretStoreService_ApplySecret_Handler,
		},
		{
			MethodName: "DeleteKeys",
			Handler:    _ExternalSecretStoreService_DeleteKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1alpha1/ess.proto",
}
